apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  instances: 1
  externalAccess:
    enabled: true
  externalDatabase:
    enabled: true
  db:
    vendor: postgres
    host: postgres-primary.keycloak.svc
    port: 5432
    usernameSecret:
      name: postgres-pguser-keycloak
      key: user
    passwordSecret:
      name: postgres-pguser-keycloak
      key: password
  hostname:
    hostname: keycloak.apps-crc.testing
  http:
    tlsSecret: keycloak-certificate
